### ISSUE TITLE
What if you have 1000 pages?

### ISSUE THREAD

**Issue by jamiegau** [joaquimnetocel/pagination-svelte#1]
Typically you use pagination of large data sets.
If I have 100000 entries and 5 items per page.
100000/5 = 20000 pages.
That's not going to work with this pagination tool.  would be 20002 buttons wide.
It would be more usable if.. a start, end with a moving indicator
For example..

Prev | 1 | ... | 402 |403 | Selected 404, click to edit | 405 | 406 | ... | 20000 | Next

Otherwise.
Nice...

**Comment by joaquimnetocel** [comment]
Problem solved on version 1.0.0 (dedicated to svelte 5). Now you can use two props: `propShortMode` and `propShortModeLimit` to activate short mode page navigations.

Take a look on the examples in the `routes` folder.
